<?php

namespace common\models;

use common\models\storage\Storage;
use Yii;
use yii\helpers\FileHelper;
use yii\web\UploadedFile;

/**
 * This is the model class for table "events".
 *
 * @property int $id
 * @property string $title
 * @property string|null $date_start
 * @property string|null $date_end
 * @property string|null $location
 * @property string|null $document
 * @property int|null $evaluation
 * @property int $student_id
 * @property int|null $user_id
 * @property int|null $status_id
 * @property int|null $type_id
 * @property string|null $comment
 *
 * @property EventStatus $status
 * @property Students $student
 * @property EventType $type
 * @property User $user
 */
class Events extends \yii\db\ActiveRecord
{
    public $file;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'events';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'student_id'], 'required'],
            [['date_start', 'date_end'], 'safe'],
            [['evaluation', 'student_id', 'user_id', 'status_id', 'type_id'], 'integer'],
            [['file',], 'file',
                'extensions' => ['pdf', 'doc', 'docx', 'rtf'],
                'checkExtensionByMimeType' => true,
                'skipOnEmpty' => true,
                'maxSize' => 5000 * 1024,
                'tooBig' => 'Лимит 5Мб'
            ],
            [['title', 'location', 'document', 'comment'], 'string', 'max' => 255],
            [['status_id'], 'exist', 'skipOnError' => true, 'targetClass' => EventStatus::className(), 'targetAttribute' => ['status_id' => 'id']],
            [['student_id'], 'exist', 'skipOnError' => true, 'targetClass' => Students::className(), 'targetAttribute' => ['student_id' => 'id']],
            [['type_id'], 'exist', 'skipOnError' => true, 'targetClass' => EventType::className(), 'targetAttribute' => ['type_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => '№ Мероприятия',
            'title' => 'Наименование',
            'date_start' => 'Дата начала',
            'date_end' => 'Дата окончания',
            'location' => 'Место проведения',
            'document' => 'Документ',
            'evaluation' => 'Оценка',
            'student_id' => '№ Студента',
            'user_id' => '№ Научного руководителя',
            'status_id' => '№ Статуса',
            'type_id' => '№ Типа мероприятия',
            'comment' => 'Комменатрий',
        ];
    }

    public function uploadFile($file, $attr)
    {
        if ($this->validate($attr)) {

            if(empty($file))
                return false;

            if(Yii::$app->controller->action->id === 'upload-events')
                $userID = Yii::$app->user->id;
            else $userID = $this->student->user_id;

            $destination = 'users/' . $userID . '/uploads/files/Научная деятельность/Мероприятия/';
            $path = Storage::getStoragePath() . $destination;
            $filename = Storage::randomFileName($file);

            if($this->document)
                unlink(Storage::getStoragePath() . $this->document);

            if (FileHelper::createDirectory($path, $mode = 0755, $recursive = true)) {
                $file->saveAs($path . $filename);
                $this->document = $destination . $filename;
            }

            return true;
        }
        return false;
    }

    public function deleteFile()
    {
        if($this->document)
        {
            $file = $this->document;
            $this->document = null;
            if($this->save())
                unlink(Storage::getStoragePath() . $file);
        }
    }

    public function beforeDelete()
    {
        $this->deleteFile();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function save($runValidation = true, $attributeNames = null)
    {
        $this->date_start = empty($this->date_start) ? null : (Yii::$app->formatter->asDate(strtotime($this->date_start), "php:Y-m-d"));
        $this->date_end = empty($this->date_end) ? null : (Yii::$app->formatter->asDate(strtotime($this->date_end), "php:Y-m-d"));

        switch (Yii::$app->controller->action->id){
            case 'upload-events':
            case 'update':
            case 'create':
                if($this->validate())
                {
                    $file = UploadedFile::getInstance($this, 'file');
                    $this->uploadFile($file, 'file');
                }
                break;
            default: break;
        }
        return parent::save($runValidation, $attributeNames);
    }

    /**
     * Gets query for [[Status]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getStatus()
    {
        return $this->hasOne(EventStatus::className(), ['id' => 'status_id']);
    }

    /**
     * Gets query for [[Student]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getStudent()
    {
        return $this->hasOne(Students::className(), ['id' => 'student_id']);
    }

    /**
     * Gets query for [[Type]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getType()
    {
        return $this->hasOne(EventType::className(), ['id' => 'type_id']);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
}
