<?php

namespace common\models;

use common\models\storage\Storage;
use Yii;
use yii\helpers\FileHelper;
use yii\web\UploadedFile;

/**
 * This is the model class for table "practics".
 *
 * @property int $id
 * @property string $title
 * @property string $place
 * @property string|null $date_start
 * @property string|null $date_end
 * @property string|null $document
 * @property string|null $diary
 * @property string|null $characteristic
 * @property int|null $evaluation
 * @property int $stud_id
 * @property string|null $comment
 *
 * @property Students $stud
 */
class Practics extends \yii\db\ActiveRecord
{
    public $file;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'practics';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'place', 'stud_id'], 'required'],
            [['date_start', 'date_end'], 'safe'],
            [['evaluation', 'stud_id'], 'integer'],
            [['evaluation'], 'integer', 'min' => 0, 'max' => 100],
            [['file',], 'file',
                'extensions' => ['pdf', 'doc', 'docx', 'rtf'],
                'checkExtensionByMimeType' => true,
                'skipOnEmpty' => true,
                'maxSize' => 5000 * 1024,
                'tooBig' => 'Лимит 5Мб'
            ],
            [['title', 'place', 'document', 'diary', 'characteristic', 'comment'], 'string', 'max' => 255],
            [['stud_id'], 'exist', 'skipOnError' => true, 'targetClass' => Students::className(), 'targetAttribute' => ['stud_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => '№ Практики',
            'title' => 'Наименование',
            'place' => 'Место проведения',
            'date_start' => 'Дата начала',
            'date_end' => 'Дата окончания',
            'document' => 'Документ',
            'diary' => 'Дневник',
            'characteristic' => 'Характеристика',
            'evaluation' => 'Оценка',
            'stud_id' => '№ Студента',
            'comment' => 'Комментарий'
        ];
    }

    public function uploadFile($file, $attr)
    {
        if ($this->validate($attr)) {

            if(empty($file))
                return false;

            if(Yii::$app->controller->action->id === 'upload-practics')
                $userID = Yii::$app->user->id;
            else $userID = $this->stud->user_id;

            $destination = 'users/' . $userID . '/uploads/files/Учебная деятельность/Практика/';
            $path = Storage::getStoragePath() . $destination;
            $filename = Storage::randomFileName($file);

            if($this->document)
                unlink(Storage::getStoragePath() . $this->document);

            if (FileHelper::createDirectory($path, $mode = 0755, $recursive = true)) {
                $file->saveAs($path . $filename);
                $this->document = $destination . $filename;
            }

            return true;
        }
        return false;
    }

    public function deleteFile()
    {
        if($this->document)
        {
            $file = $this->document;
            $this->document = null;
            if($this->save())
                unlink(Storage::getStoragePath() . $file);
        }
    }

    public function beforeDelete()
    {
        $this->deleteFile();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function save($runValidation = true, $attributeNames = null)
    {
        $this->date_start = empty($this->date_start) ? null : (Yii::$app->formatter->asDate(strtotime($this->date_start), "php:Y-m-d"));
        $this->date_end = empty($this->date_end) ? null : (Yii::$app->formatter->asDate(strtotime($this->date_end), "php:Y-m-d"));

        switch (Yii::$app->controller->action->id){
            case 'upload-practics':
            case 'update':
            case 'create':
                if($this->validate())
                {
                    $file = UploadedFile::getInstance($this, 'file');
                    $this->uploadFile($file, 'file');
                }
                break;
            default: break;
        }
        return parent::save($runValidation, $attributeNames);
    }

    /**
     * Gets query for [[Stud]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getStud()
    {
        return $this->hasOne(Students::className(), ['id' => 'stud_id']);
    }
}
